### PR TITLE
Use UTC in generating DOS date

### LINKED ISSUE #14: Use UTC in generating DOS date
[zipUtil.dateToDos()](https://github.com/archiverjs/node-compress-commons/blob/744af18168ed283e2ee362ab4d20b62814dbf307/lib/archivers/zip/util.js#L11) should use UTC variants (getUTCFullYear(), getUTCMonth()...) of the Date methods to take into account timezone information in the supplied date.

### PR DESCRIPTION
**Pull request by joelmukuthu**
Closes #14

### CODE REVIEW

**Comment by joelmukuthu** [comment]
Any word on this? This fix is quite critical, especially for tests. If you're running tests to verify that the created archive is exactly the same as an archive that you have created manually, and you happen to run the test on a machine whose timezone is not the same as your machine's timezone (e.g. on a CI platform), then the test will fail. This happens because the last-modified time of the entries in the archive are different.
Since DOS time does not have timezone information, you should use universal time for the entries.

**Comment by ctalkington** [comment]
ive went back and forth on this in the past used to patch my tests to account for such too. hum let me think on this for a bit longer; i do see merit in it... lets just do it now :)

**Comment by joelmukuthu** [comment]
great, thanks! any plans of an upcoming release?

**Comment by ctalkington** [comment]
yep, just got sidetracked

**Comment by joelmukuthu** [comment]
perfect! thanks

**Pull request merged**
